# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "495075348a7f22b2d205b5017568c4cd"
application_url = "https://thailand-hugh-cw-generated.trycloudflare.com"
embedded = true
name = "Test App"
handle = "test-app-11686"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://thailand-hugh-cw-generated.trycloudflare.com/auth/callback",
  "https://thailand-hugh-cw-generated.trycloudflare.com/auth/shopify/callback",
  "https://thailand-hugh-cw-generated.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
